name: Build EcoEnchants

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - id: latestTag
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: Auxilor
        repo: EcoEnchants
        excludes: draft

    - name: Download EcoEnchants
      run: git clone https://github.com/Auxilor/EcoEnchants --branch ${{ steps.latestTag.outputs.release }}

    - name: Run Gradle tasks
      run: |
        cd EcoEnchants
        ./gradlew clean
        ./gradlew build

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: "EcoEnchants v${{ steps.latestTag.outputs.release }}"
        tag_name: ${{ steps.latestTag.outputs.release }}
        body: |
          > [!NOTE]
          > This release is based on [v${{ steps.latestTag.outputs.release }} of Auxilor/EcoEnchants](https://github.com/Auxilor/EcoEnchants/releases/tag/${{ steps.latestTag.outputs.release }}).
          ${{ steps.latestTag.outputs.description }}
        generate_release_notes: false
        token: ${{ secrets.PAT }}
        files: EcoEnchants/build/libs/*.jar